/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _DevRoute } from '../pages/dev';
import { Route as _DexRoute } from '../pages/dex';
import { Route as _EggsRoute } from '../pages/eggs';
import { Route as _ExchangeRoute } from '../pages/exchange';
import { Route as _GameRoute } from '../pages/game';
import { Route as _GuideRoute } from '../pages/guide';
import { Route as _IndexRoute } from '../pages/';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/dev': (typeof _DevRoute)['_inputType'];
    '/dex': (typeof _DexRoute)['_inputType'];
    '/eggs': (typeof _EggsRoute)['_inputType'];
    '/exchange': (typeof _ExchangeRoute)['_inputType'];
    '/game': (typeof _GameRoute)['_inputType'];
    '/guide': (typeof _GuideRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/dev': (typeof _DevRoute)['_outputType'];
    '/dex': (typeof _DexRoute)['_outputType'];
    '/eggs': (typeof _EggsRoute)['_outputType'];
    '/exchange': (typeof _ExchangeRoute)['_outputType'];
    '/game': (typeof _GameRoute)['_outputType'];
    '/guide': (typeof _GuideRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
  }
}
